apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tojo5vg4k-go
  janus-idp.io/tekton: tojo5vg4k-go
  backstage.io/kubernetes-id: tojo5vg4k-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tojo5vg4k-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
